chore: add log info for commands

diff --git a/commands/remove b/commands/remove
--- a/commands/remove
+++ b/commands/remove
@@ -17,8 +17,15 @@ core() {
     exit 1
   fi
 
-  multipass delete $name
-  multipass purge
+  log::info "[$(timestamp)] removing vm: $name ..."
+
+  multipass delete $name && multipass purge
+  
+  if [ "$?" = "0" ]; then
+    log::success "[$(timestamp)] succeed to remove vm: $name ."
+  else
+    log::success "[$(timestamp)] failed to remove vm: $name ."
+  fi
 }
 
 run() {
diff --git a/commands/restart b/commands/restart
--- a/commands/restart
+++ b/commands/restart
@@ -17,7 +17,13 @@ core() {
     exit 1
   fi
 
+  log::info "[$(timestamp)] restarting vm: $name ..."
   multipass restart $name
+  if [ "$?" = "0" ]; then
+    log::success "[$(timestamp)] succeed to restart vm: $name ."
+  else
+    log::success "[$(timestamp)] failed to restart vm: $name ."
+  fi
 }
 
 run() {
diff --git a/commands/start b/commands/start
--- a/commands/start
+++ b/commands/start
@@ -17,7 +17,13 @@ core() {
     exit 1
   fi
 
+  log::info "[$(timestamp)] starting vm: $name ..."
   multipass launch --cpus 2 --mem 2G --name $name ubuntu
+  if [ "$?" = "0" ]; then
+    log::success "[$(timestamp)] succeed to start vm: $name ."
+  else
+    log::success "[$(timestamp)] failed to start vm: $name ."
+  fi
 }
 
 run() {
diff --git a/commands/stop b/commands/stop
--- a/commands/stop
+++ b/commands/stop
@@ -17,7 +17,13 @@ core() {
     exit 1
   fi
 
+  log::info "[$(timestamp)] stopping vm: $name ..."
   multipass stop $name
+  if [ "$?" = "0" ]; then
+    log::success "[$(timestamp)] succeed to stop vm: $name ."
+  else
+    log::success "[$(timestamp)] failed to stop vm: $name ."
+  fi
 }
 
 run() {
